Repository DFE-Digital/early-careers-framework, pull requests merged in 2021-06, with the labels that each got.

#419 CPDRP-296: GIAS email updates
  app/jobs/school_email_update_job.rb
  app/services/school_data_importer.rb
  lib/tasks/cron.rake
  spec/jobs/school_email_update_job_spec.rb
  spec/services/school_data_importer_spec.rb
Labels: QA

#392 Sending partnership challenged email notifications
  app/forms/challenge_partnership_form.rb
  app/mailers/lead_provider_mailer.rb
  app/models/cron_job_scheduler.rb
  spec/forms/challenge_partnership_form_spec.rb
  spec/mailers/lead_provider_mailer_spec.rb
  spec/models/cron_job_scheduler_spec.rb
  spec/services/partnership_notification_service_spec.rb
  spec/support/active_job.rb
  spec/support/delayed_job.rb
Labels: QA

#414 CPDRP-275: Add UTM parameters to all links to the service in emails
  app/controllers/admin/administrators/administrators_controller.rb
  app/forms/supplier_user_form.rb
  app/models/nomination_email.rb
  app/services/create_induction_tutor.rb
  app/services/partnership_notification_service.rb
  app/services/utm_service.rb
  lib/devise/strategies/passwordless_authenticatable.rb
  lib/tasks/manage_admins.rake
  spec/requests/admin/administrators/administrators_spec.rb
  spec/tasks/manage_admins_spec.rb
Labels: QA

#438 CPDRP-374: send chaser emails
  app/models/school.rb
  app/services/invite_schools.rb
  lib/tasks/schools.rake
  spec/models/school_spec.rb
  spec/services/invite_schools_spec.rb
Labels: QA

#476 CPDRP-343: Track CSV errors in GA data layer
  app/views/lead_providers/report_schools/csv/errors.html.erb
  app/views/lead_providers/report_schools/csv/show.html.erb
  spec/requests/lead_providers/report_schools/csv_spec.rb
Labels: QA

#429 Give admins the ability to monitor single school participants
  app/controllers/admin/participants_controller.rb
  app/controllers/admin/schools/participants_controller.rb
  app/models/user.rb
  app/policies/participant_policy.rb
  app/views/admin/participants/show.html.erb
  app/views/admin/schools/participants/index.html.erb
  app/views/admin/schools/shared/_navigation.html.erb
  config/routes.rb
  spec/cypress/app_commands/scenarios/admin/school_participants.rb
  spec/cypress/integration/admin/ViewSchoolParticipants.feature
  spec/cypress/support/step_definitions/common-navigation.js
  spec/models/user_spec.rb
  spec/requests/admin/participants_request_spec.rb
  spec/requests/admin/schools/participants_spec.rb
Labels: QA

#467 CPDRP-350 opt out of ecf notifications
  app/controllers/concerns/nomination_email_token_consumer.rb
  app/controllers/nominations/choose_how_to_continue_controller.rb
  app/controllers/nominations/nominate_induction_coordinator_controller.rb
  app/controllers/schools/choose_programme_controller.rb
  app/controllers/schools/cohorts_controller.rb
  app/forms/induction_choice_form.rb
  app/forms/nominate_how_to_continue_form.rb
  app/models/cohort.rb
  app/models/school_cohort.rb
  app/views/nominations/choose_how_to_continue/new.html.erb
  app/views/nominations/nominate_induction_coordinator/start.html.erb
  app/views/nominations/nominate_induction_coordinator/start_nomination.html.erb
  app/views/schools/choose_programme/choice_saved_design_our_own.html.erb
  app/views/schools/choose_programme/show.html.erb
  app/views/schools/cohorts/programme_choice_design_our_own.html.erb
  app/views/schools/cohorts/programme_choice_no_early_career_teachers.html.erb
  app/views/schools/dashboard/show.html.erb
  app/views/shared/_diy_what_you_can_do_now_info.html.erb
  app/views/shared/choice_saved_no_early_career_teachers.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210602115738_add_opt_out_of_updates_to_school_cohorts.rb
  db/schema.rb
  spec/cypress/integration/nominations/ChooseHowToContinue.feature
  spec/cypress/integration/nominations/NominateInductionCoordinator.feature
  spec/cypress/integration/schools/ChooseProgramme.feature
  spec/cypress/support/step_definitions/common-interaction.js
  spec/cypress/support/step_definitions/common-navigation.js
  spec/forms/induction_choice_form_spec.rb
  spec/forms/nominate_how_to_continue_form_spec.rb
  spec/models/cohort_spec.rb
  spec/models/school_cohort_spec.rb
  spec/requests/nominations/choose_how_to_continue_spec.rb
  spec/requests/nominations/nominate_induction_coordinator_spec.rb
  spec/requests/schools/programme_choice_spec.rb
Labels: QA

#501 CPDTP-196 Adding in the schema_validator to the API
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/participant_declarations_controller.rb
  app/services/calculation_orchestrator.rb
  app/services/contract_event_payment_calculator.rb
  app/services/induct_participant.rb
  app/services/participant_event_aggregator.rb
  app/services/record_participant_event.rb
  etc/schema/0.1/ecf/participant_declarations/create/request_schema.json
  etc/schema/0.2/ecf/participant_declarations/create/request_schema.json
  etc/schema/1.0/ecf/contracts/create/request_schema.json
  lib/has_di_parameters.rb
  lib/json_schema/validate_body_against_schema.rb
  lib/json_schema/validation.rb
  lib/json_schema/validator_adapter.rb
  lib/json_schema/version_event_file_name.rb
  lib/payment_calculator/ecf/contract/output_payment_calculations.rb
  lib/payment_calculator/ecf/contract/service_fee_calculations.rb
  lib/payment_calculator/ecf/output_payment_aggregator.rb
  lib/payment_calculator/ecf/payment_calculation.rb
  spec/docs/participant_declarations_spec.rb
  spec/lib/has_di_parameters_spec.rb
  spec/lib/json_schema/validator_adapter_spec.rb
  spec/lib/json_schema/version_event_file_name_spec.rb
  spec/lib/payment_calculator/ecf/payment_calculation_spec.rb
  spec/lib/payment_calculator/turnip_steps/ecf/output_payments_steps.rb
  spec/lib/payment_calculator/turnip_steps/ecf/service_fees_steps.rb
  spec/models/participation_record_spec.rb
  spec/requests/api/v1/provider_events_spec.rb
  spec/services/calculation_orchestrator_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api_spec.json
Labels: track-and-pay📈💷

#533 Refactor - rename variable in test to match class name
  lib/payment_calculator/ecf/payment_calculation.rb
Labels: track-and-pay📈💷

#544 inject DQT creds for staging and prod
  config/credentials/production.yml.enc
  config/credentials/staging.yml.enc
  config/environments/production.rb
  config/environments/staging.rb
Labels: blocked-merge

#557 CPDTP-183 Enable a11y and percy checks for sandbox landing page
  spec/cypress/integration/Sandbox.feature
  spec/cypress/support/step_definitions/common-navigation.js
Labels: track-and-pay📈💷

#559 CPDTP-109 Update output to clean up the display
  lib/tasks/payment_breakdown.rake
Labels: track-and-pay📈💷

#542 CPDRP-345: Induction coordinators have multiple schools
  app/controllers/admin/schools/induction_coordinators_controller.rb
  app/controllers/nominations/nominate_induction_coordinator_controller.rb
  app/controllers/schools/base_controller.rb
  app/controllers/schools/choose_programme_controller.rb
  app/controllers/schools/dashboard_controller.rb
  app/forms/nominate_induction_tutor_form.rb
  app/helpers/application_helper.rb
  app/helpers/school_breadcrumbs_helper.rb
  app/services/create_induction_tutor.rb
  app/views/admin/schools/induction_coordinators/name_different.html.erb
  app/views/nominations/nominate_induction_coordinator/email_used.html.erb
  app/views/nominations/nominate_induction_coordinator/name_different.html.erb
  app/views/schools/choose_programme/advisory.html.erb
  app/views/schools/cohorts/add_participants.html.erb
  app/views/schools/cohorts/programme_choice.html.erb
  app/views/schools/cohorts/programme_choice_design_our_own.html.erb
  app/views/schools/cohorts/programme_choice_no_early_career_teachers.html.erb
  app/views/schools/cohorts/show.html.erb
  app/views/schools/core_programme/materials/info.html.erb
  app/views/schools/core_programme/materials/show.html.erb
  app/views/schools/dashboard/index.html.erb
  app/views/schools/dashboard/show.html.erb
  app/views/schools/participants/index.html.erb
  app/views/schools/participants/show.html.erb
  app/views/schools/partnerships/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/cypress/app_commands/scenarios/schools/multiple_schools.rb
  spec/cypress/integration/admin/InductionCoordinatorManagment.feature
  spec/cypress/integration/nominations/NominateInductionCoordinator.feature
  spec/cypress/integration/schools/MultipleSchools.feature
  spec/factories/nomination_email.rb
  spec/forms/nominate_induction_tutor_form_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/school_breadcrumbs_helper_spec.rb
  spec/requests/admin/schools/induction_coordinators_spec.rb
  spec/requests/nominations/nominate_induction_coordinator_spec.rb
  spec/requests/schools/dashboard_spec.rb
  spec/services/create_induction_tutor_spec.rb
  spec/spec_helper.rb
Labels: QA

#555 Add induction tutor email to school search
  app/controllers/admin/schools_controller.rb
  app/views/admin/schools/index.html.erb
  spec/cypress/integration/admin/SchoolManagment.feature
  spec/requests/admin/schools_spec.rb
Labels: QA

#585 CPDTP-195 Add migration to backfill ECT profile uplift data
  db/migrate/20210618160328_backfill_profile_uplift_data.rb
Labels: track-and-pay📈💷

#531 CPDRP-443 notification banners for opted-out schools
  app/components/school_recruited_transition_component.rb
  app/jobs/partnership_activation_job.rb
  spec/components/school_recruited_transition_component_spec.rb
  spec/cypress/app_commands/scenarios/school_opted_out_but_was_recruited.rb
  spec/cypress/integration/schools/SeeChallengeBanners.feature
  spec/jobs/partnership_activation_job_spec.rb
Labels: QA

#597 CPDTP-204 Don't output mentor ids in sandbox seed output
  db/seeds/sandbox_data.rb
Labels: track-and-pay📈💷

#596 CPDTP-204 Fix issue with undefined local variable RecordParticipantEvent
  app/services/record_participant_event.rb
  spec/requests/api/v1/provider_events_spec.rb
  spec/services/record_participant_service_spec.rb
Labels: track-and-pay📈💷

#601 CPDTP-204 Return `id` of newly created declaration in API
  app/controllers/api/v1/participant_declarations_controller.rb
  app/services/record_participant_event.rb
  spec/docs/participant_declarations_spec.rb
  spec/requests/api/v1/provider_events_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api_spec.json
Labels: track-and-pay📈💷
