Repository DFE-Digital/early-careers-framework, pull requests merged in 2021-07, with the labels that each got.

#610 Stable API tokens in seeds for development
  app/models/api_token.rb
  db/seeds/initial_seed.rb
  db/seeds/sandbox_data.rb
Labels: track-and-pay📈💷

#618 Document the local authority to district missing link
  app/models/local_authority_district.rb
Labels: track-and-pay📈💷

#622 CDPTP-224 Remove lead_provider from profile_declarations
  app/models/profile_declaration.rb
  db/migrate/20210701000300_remove_lead_provider_from_profile_declarations.rb
  db/schema.rb
Labels: track-and-pay📈💷

#625 CPDTP-224 add mentors to participant declarations
  app/controllers/api/v1/participant_declarations_controller.rb
  app/models/early_career_teacher_profile.rb
  app/models/mentor_profile.rb
  app/models/participant_declaration.rb
  app/models/profile_declaration.rb
  app/services/record_participant_declaration.rb
  app/services/record_participant_event.rb
  db/migrate/20210701000400_add_user_id_to_participant_declarations.rb
  db/migrate/20210701000420_change_user_id_to_be_not_null.rb
  db/migrate/20210701000430_remove_early_career_teacher_profile_id_column.rb
  db/schema.rb
  spec/docs/participant_declarations_spec.rb
  spec/factories/mentor_profiles.rb
  spec/factories/participant_declaration.rb
  spec/factories/participant_declarations.rb
  spec/factories/profile_declaration.rb
  spec/models/participant_declaration_spec.rb
  spec/requests/api/v1/provider_events_spec.rb
  spec/services/calculation_orchestrator_spec.rb
  spec/services/participant_event_aggregator_service_spec.rb
  spec/services/record_participant_declaration_service_spec.rb
Labels: track-and-pay📈💷

#615 CPDRP-548: Induction tutors change participant details
  app/controllers/schools/participants_controller.rb
  app/policies/participant_policy.rb
  app/views/schools/participants/edit_email.html.erb
  app/views/schools/participants/edit_name.html.erb
  app/views/schools/participants/email_used.html.erb
  app/views/schools/participants/show.html.erb
  config/routes.rb
  spec/cypress/integration/schools/ManageParticipants.feature
  spec/cypress/support/step_definitions/common-navigation.js
  spec/requests/schools/participants_request_spec.rb
Labels: blocked-merge

#617 CPDTP-232 Add a rake task for generating sandbox mentors
  db/seeds.rb
  db/seeds/sandbox_data.rb
  lib/tasks/sandbox_data.rake
Labels: track-and-pay📈💷

#645 Add documentation
  README.md
Labels: documentation

#628 CPDTP-304 Allow reset of sandbox data
  lib/tasks/safe_reset.rake
Labels: track-and-pay📈💷

#649 Switch the sandbox_data seeding to use the new structure
  lib/tasks/sandbox_data.rake
Labels: track-and-pay📈💷

#657 CPDRP-578: Fix change induction coordinator logic
  app/services/create_induction_tutor.rb
  spec/services/create_induction_tutor_spec.rb
Labels: QA

#660 Change production db to high availability
  terraform/workspace-variables/production.tfvars
Labels: blocked-merge

#672 Remove unused code - delegate of bands to contract
  lib/payment_calculator/ecf/contract/output_payment_calculations.rb
Labels: track-and-pay📈💷

#653 CPDRP-527 Opt out schools that report partnership as no ECTs
  app/forms/challenge_partnership_form.rb
  spec/forms/challenge_partnership_form_spec.rb
Labels: QA

#689 Erb guidance page for lead providers
  app/views/lead_providers/content/partnership_guide.html.erb
  app/views/lead_providers/content/partnership_guide.html.md
  app/views/lead_providers/guidance/ecf_usage.html.erb
  app/views/lead_providers/guidance/ecf_usage.md
  app/views/lead_providers/guidance/help.html.erb
  app/views/lead_providers/guidance/help.md
  app/views/lead_providers/guidance/index.html.erb
  app/views/lead_providers/guidance/index.md
  app/views/lead_providers/guidance/release_notes.html.erb
  app/views/lead_providers/guidance/release_notes.md
  config/initializers/markdown_handler.rb
Labels: documentation

#708 NPQ API reference docs
  spec/components/api_docs/operation_component_spec.rb
  spec/docs/npq_applications_spec.rb
  spec/docs/participant_declarations_spec.rb
  spec/docs/participants_spec.rb
  spec/presenters/api_docs/api_operation_spec.rb
  spec/presenters/api_docs/api_reference_spec.rb
  spec/support/open_api_example_specification.rb
  swagger/v1/api_spec.json
  swagger/v1/component_schemas/EcfParticipant.yml
  swagger/v1/component_schemas/EcfParticipantAttributes.yml
  swagger/v1/component_schemas/EcfParticipantCsvRow.yml
  swagger/v1/component_schemas/ListFilter.yml
  swagger/v1/component_schemas/MultipleEcfParticipantsCsvResponse.yml
  swagger/v1/component_schemas/MultipleEcfParticipantsResponse.yml
  swagger/v1/component_schemas/MultipleNpqApplicationsCsvResponse.yml
  swagger/v1/component_schemas/MultipleNpqApplicationsResponse.yml
  swagger/v1/component_schemas/NpqApplication.yml
  swagger/v1/component_schemas/NpqApplicationAttributes.yml
  swagger/v1/component_schemas/NpqApplicationCsvRow.yml
  swagger/v1/component_schemas/ParticipantDeclarationRecordedResponse.yml
  swagger/v1/component_schemas/ParticipantFilter.yml
  swagger/v1/template.yml
Labels: documentation

#713 CPDTP-342 Skip mock login for unknown email instead of raising
  app/controllers/users/sessions_controller.rb
  spec/requests/users/sessions_spec.rb
Labels: track-and-pay📈💷

#718 NPQ sandbox guidance
  app/controllers/lead_providers/guidance_controller.rb
  app/views/layouts/guidance_markdown.html.erb
  app/views/lead_providers/content/index.html.erb
  app/views/lead_providers/content/partnership_guide.html.erb
  app/views/lead_providers/guidance/ecf_usage.html.erb
  app/views/lead_providers/guidance/index.html.erb
  app/views/lead_providers/guidance/npq_usage.html.erb
  app/views/lead_providers/guidance/reference.html.erb
  app/views/lead_providers/guidance/release_notes.html.erb
  app/views/sandbox/show.html.erb
  config/routes.rb
  spec/cypress/integration/Sandbox.feature
  spec/cypress/integration/lead_providers/Guidance.feature
  spec/cypress/integration/lead_providers/PartnershipGuidance.feature
  spec/cypress/support/step_definitions/common-navigation.js
  spec/docs/npq_applications_spec.rb
  spec/docs/participants_spec.rb
  spec/requests/lead_providers/ecf_usage_spec.rb
  spec/requests/lead_providers/npq_usage_spec.rb
  spec/requests/lead_providers/partnership_guide_spec.rb
  spec/requests/sandbox_spec.rb
  swagger/v1/api_spec.json
  swagger/v1/component_schemas/MultipleEcfParticipantsCsvResponse.yml
  swagger/v1/component_schemas/MultipleEcfParticipantsResponse.yml
  swagger/v1/component_schemas/Pagination.yml
Labels: documentation

#703 CPDRP-622 Prevent NPQ registration from blocking ECT/mentor registration
  app/controllers/admin/schools/participants_controller.rb
  app/forms/schools/add_participant_form.rb
  app/models/participant_profile.rb
  app/models/user.rb
  app/policies/participant_policy.rb
  app/services/mentors/create.rb
  db/seeds/dummy_structures.rb
  spec/forms/schools/add_participant_form_spec.rb
  spec/models/user_spec.rb
  spec/policies/participant_policy_spec.rb
Labels: QA

#723 CPDTP-302 Convert some of the turnip feature tests to pure rspec
  spec/lib/payment_calculator/ecf/contract/service_fee_calculations_spec.rb
  spec/lib/payment_calculator/turnip_features/ecf/call_off_contract.feature
  spec/lib/payment_calculator/turnip_features/ecf/service_fees.feature
  spec/lib/payment_calculator/turnip_steps/ecf/call_off_contract_steps.rb
Labels: track-and-pay📈💷

#732 CPDRP-573: admins delete participants
  app/controllers/admin/participants_controller.rb
  app/controllers/admin/schools/participants_controller.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/policies/participant_profile_policy.rb
  app/serializers/participant_serializer.rb
  app/services/feature_flag.rb
  app/views/admin/participants/destroy_success.html.erb
  app/views/admin/participants/remove.html.erb
  app/views/admin/participants/show.html.erb
  app/views/admin/schools/participants/index.html.erb
  config/routes.rb
  spec/cypress/integration/admin/ParticipantManagment.feature
  spec/cypress/integration/admin/ViewSchoolParticipants.feature
  spec/cypress/support/step_definitions/common-navigation.js
  spec/models/user_spec.rb
  spec/policies/participant_profile_policy_spec.rb
  spec/requests/admin/participants_request_spec.rb
  spec/requests/admin/participants_spec.rb
  spec/requests/admin/schools/participants_spec.rb
  spec/serializers/participant_serializer_spec.rb
Labels: QA

#735 CPDTP-329 Add in model validations for participant_declarations
  app/models/participant_declaration.rb
  app/models/participant_declaration/ecf.rb
  app/models/participant_declaration/npq.rb
  db/seeds/initial_seed.rb
  spec/factories/participant_declaration.rb
  spec/models/participant_declaration_spec.rb
  spec/models/profile_declaration_spec.rb
  spec/requests/api/v1/participant_declarations_spec.rb
  spec/services/calculation_orchestrator_spec.rb
  spec/services/feature_flag_spec.rb
  spec/services/participant_event_aggregator_service_spec.rb
Labels: track-and-pay📈💷

#736 Issue#336 Stop the cohorts_validation using break from within a validation proc
  app/forms/delivery_partner_form.rb
Labels: track-and-pay📈💷

#739 CPDTP-348 Create lead provider index page for finance users
  app/controllers/finance/base_controller.rb
  app/controllers/finance/lead_providers_controller.rb
  app/policies/finance_profile_policy.rb
  app/views/finance/lead_providers/index.html.erb
  config/routes.rb
  spec/cypress/app_commands/scenarios/finance_lead_providers.rb
  spec/cypress/integration/finance/Finance.feature
  spec/helpers/application_helper_spec.rb
  spec/policies/finance_profile_policy_spec.rb
  spec/requests/finance/lead_providers_controller_spec.rb
Labels: track-and-pay📈💷

#747 Add code-doc to help avoid further `LeadProvider` naming confusion
  app/models/lead_provider.rb
Labels: track-and-pay📈💷

#774 Rename Z2H heading in readme
  README.md
Labels: track-and-pay📈💷
