Repository DFE-Digital/early-careers-framework, pull requests merged in 2023-09, with the labels that each got.

#3898 Remove staging/development environment workflows
  .github/workflows/build_docker_image.yml
  .github/workflows/deploy_monitoring_dev.yml
  .github/workflows/deploy_monitoring_staging.yml
  .github/workflows/deploy_to_sandbox.yml
  .github/workflows/deploy_to_staging.yml
  terraform/workspace-variables/dev.tfvars
  terraform/workspace-variables/dev_app_env.yml
  terraform/workspace-variables/review_app_env.yml
  terraform/workspace-variables/staging.tfvars
  terraform/workspace-variables/staging_app_env.yml
Labels: azure-migration

#3900 Remove the `deployed_development` environment
  .rubocop.yml
  Gemfile
  README.md
  app/controllers/users/sessions_controller.rb
  app/helpers/phase_banner_helper.rb
  app/middlewares/time_traveler.rb
  app/models/analytics/base_record.rb
  config/credentials/deployed_development.yml.enc
  config/database.yml
  config/environments/deployed_development.rb
  config/initializers/sentry.rb
  config/seed_quantities.yml
  db/legacy_seeds/dummy_structures.rb
  db/new_seeds/base/add_api_tokens.rb
  db/new_seeds/base/add_environment_specific_data.rb
  db/new_seeds/base/add_feature_flags.rb
  db/seeds.rb
  lib/tasks/safe_reset.rake
  spec/helpers/phase_banner_helper_spec.rb
Labels: azure-migration

#3955 Update our Redis instance to standard/premium in AKS
  terraform/aks/databases.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: azure-migration

#3954 Remove sandbox PaaS deployment and database backup
  .github/workflows/backup-paas-schedule.yml
  .github/workflows/deploy_to_production.yml
  .github/workflows/deploy_to_sandbox.yml
  terraform/workspace-variables/sandbox.tfvars
  terraform/workspace-variables/sandbox_app_env.yml
Labels: blocked-merge, azure-migration

#3946 Add participant presenter to change_log_controller
  app/controllers/admin/participants/change_log_controller.rb
  spec/requests/admin/participants/change_log_spec.rb
Labels: bug

#3959 Change queue capacity to 1 for prod Redis
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: azure-migration

#3952 Make prod restore target the actual prod database
  .github/actions/backup-paas-database/action.yml
Labels: azure-migration

#3977 Reinstate the database backup upload
  .github/actions/backup-paas-database/action.yml
Labels: azure-migration

#3982 Add a test notify key for the review env
  config/credentials/review.yml.enc
Labels: azure-migration

#3988 Add back missing variables, these are required for sending emails
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: azure-migration

#3987 Add statuscake monitoring to AKS
  .github/actions/deploy-environment-to-aks/action.yml
  .github/workflows/aks_deploy.yml
  Makefile
  terraform/aks/monitoring.tf
  terraform/aks/providers.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: azure-migration

#3990 Remove ability to upload CSV files to AWS
  Gemfile
  Gemfile.lock
  app/controllers/lead_providers/report_schools/csv_controller.rb
  app/jobs/sync_partnership_csv_upload_job.rb
  app/models/partnership_csv_upload.rb
  config/environments/production.rb
  config/environments/sandbox.rb
  config/environments/staging.rb
  config/initializers/01_vcap_services.rb
  config/initializers/02_vcap_services.rb
  config/storage.yml
  db/migrate/20230913213845_drop_active_storage_tables.rb
  db/schema.rb
  spec/factories/partnership_csv_upload.rb
  spec/jobs/sync_partnership_csv_upload_job_spec.rb
  spec/models/partnership_csv_upload_spec.rb
  spec/requests/lead_providers/report_schools/csv_spec.rb
Labels: azure-migration

#4003 Increase the webapp/worker replicas in production
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: azure-migration

#3980 Remove production PaaS deployment and database backup
  .github/workflows/backup-paas-schedule.yml
  .github/workflows/deploy_to_production.yml
  app/components/banners/maintenance_component.rb
  terraform/workspace-variables/production.tfvars
  terraform/workspace-variables/production_app_env.yml
Labels: blocked-merge, azure-migration

#3986 [605] Move production domain from PaaS to AKS
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_production_aks_backend.tfvars
Labels: azure-migration

#3992 Move suffix dash to environment assignment
  Makefile
  terraform/aks/application.tf
Labels: azure-migration

#3965 Add dfe-analytics BigQuery integration
  .env.template
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/services/feature_flag.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/analytics_pii.yml
  config/credentials/production.yml.enc
  config/credentials/review.yml.enc
  config/credentials/sandbox.yml.enc
  config/credentials/staging.yml.enc
  config/initializers/dfe_analytics.rb
  config/sidekiq.yml
  spec/rails_helper.rb
  spec/requests/dfe_analytics_spec.rb
  spec/services/feature_flag_spec.rb
Labels: blocked-merge

#4038 Swap old PaaS URL for new AKS URL
  docs/source/get-started.html.md
  docs/source/release-notes.html.md
  swagger/v1/api_spec.json
  swagger/v1/template.yml
  swagger/v2/api_spec.json
  swagger/v2/template.yml
  swagger/v3/api_spec.json
  swagger/v3/template.yml
Labels: azure-migration

#4036 Update analyics instructions for Azure
  analytics_queries/README
Labels: azure-migration

#4007 Remove old workflows and actions
  .github/actions/backup-paas-database/action.yml
  .github/actions/restore-paas-database/action.yml
  .github/workflows/build_docker_image.yml
  .github/workflows/deploy_monitoring.yml
  .github/workflows/deploy_monitoring_production.yml
  .github/workflows/run_task_dev.yml
Labels: azure-migration
