Repository DFE-Digital/early-careers-framework, pull requests merged in 2023-02, with the labels that each got.

#2981 Critical stats task
  app/controllers/admin/participants/event_history_controller.rb
  app/services/participants/history_builder.rb
  app/views/admin/participants/event_history/show.html.erb
  app/views/schools/participants/show.html.erb
  config/routes.rb
  lib/tasks/compare/critical_data_changed_checker.rake
  lib/tasks/compare/event_history_analyser.rake
  spec/services/participants/history_builder_spec.rb
  spec/support/with_support_for_ect_examples.rb
Labels: blocked-merge, test-pr

#2960 [CST-1240] Standardise retrieving 'relevant' induction records
  app/models/induction_record.rb
  app/models/participant_profile/ecf.rb
  app/services/induction/find_by.rb
  app/services/record_declaration.rb
  app/validators/induction_record_validator.rb
  db/new_seeds/scenarios/participants/ects/ect.rb
  db/new_seeds/scenarios/schools/school.rb
  spec/models/induction_record_spec.rb
  spec/services/api/v1/ecf/induction_records_query_spec.rb
  spec/services/induction/find_by_spec.rb
Labels: blocked-merge

#3027 Update GitHub actions to remove warnings about node 12
  .github/common_environment.yml
  .github/workflows/brakeman-analysis.yml
  .github/workflows/deploy_monitoring.yml
  .github/workflows/deploy_monitoring_dev.yml
  .github/workflows/deploy_monitoring_production.yml
  .github/workflows/deploy_monitoring_staging.yml
  .github/workflows/deploy_to_dev.yml
  .github/workflows/deploy_to_production.yml
  .github/workflows/deploy_to_sandbox.yml
  .github/workflows/deploy_to_staging.yml
  .github/workflows/destroy.yml
  .github/workflows/force_destroy.yml
  .github/workflows/lint.yml
  .github/workflows/review.yml
  .github/workflows/run_task_dev.yml
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, github_actions
