Repository DFE-Digital/early-careers-framework, pull requests merged in 2023-08, with the labels that each got.

#3759 Add missing database extensions to Azure
  terraform/aks/databases.tf
Labels: azure-migration

#3753 Add config for staging env in AKS
  .github/actions/deploy-environment-to-aks/action.yml
  .github/workflows/aks_destroy_review.yml
  Gemfile
  Makefile
  app/controllers/users/sessions_controller.rb
  app/middlewares/time_traveler.rb
  config/environments/staging.rb
  config/seed_quantities.yml
  db/new_seeds/base/add_api_tokens.rb
  db/new_seeds/base/add_environment_specific_data.rb
  db/new_seeds/base/add_feature_flags.rb
  db/seeds.rb
  global_config/staging_aks.sh
  lib/tasks/safe_reset.rake
  terraform/aks/terraform.tf
  terraform/aks/workspace_variables/README.md
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks_backend.tfvars
Labels: azure-migration, review-app

#3770 Remove continue-on-error from staging deploy step
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3774 Revert "Remove continue-on-error from staging deploy step"
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3778 Revert "Revert "Remove continue-on-error from staging deploy step""
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3790 Add Cypress to the review workflow
  .github/workflows/aks_deploy.yml
  .github/workflows/cypress.yml
  .github/workflows/rspec.yml
Labels: azure-migration

#3799 Remove the old test workflow
  .github/workflows/aks_deploy.yml
  .github/workflows/test.yml
Labels: azure-migration

#3802 Add sandbox and production envs
  .github/workflows/aks_deploy.yml
  .gitignore
  Makefile
  app/models/analytics/base_record.rb
  config/database.yml
  config/environments/production.rb
  config/environments/sandbox.rb
  global_config/production_aks.sh
  global_config/sandbox_aks.sh
  global_config/staging_aks.sh
  terraform/aks/application.tf
  terraform/aks/databases.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/production_aks_backend.tfvars
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks_backend.tfvars
Labels: azure-migration

#3813 Make prod deploy continue-on-error
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3814 Remove the development env from AKS
  Makefile
  global_config/development_aks.sh
  terraform/aks/workspace_variables/development_aks.tfvars.json
  terraform/aks/workspace_variables/development_aks_backend.tfvars
Labels: azure-migration, review-app

#3817 Fix the terraform-destroy step
  .github/workflows/aks_destroy_review.yml
Labels: azure-migration, review-app

#3818 [550] Custom domains
  .gitignore
  .tool-versions
  global_config/cpd_ecf_domain.sh
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_development_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_production_aksbackend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_sandbox_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_sandbox_aks_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_staging.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_staging_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/cpd_ecf_staging_aks_backend.tfvars
  terraform/custom_domains/infrastructure/.terraform.lock.hcl
  terraform/custom_domains/infrastructure/terraform.tf
Labels: devops

#3824 Remove continue-on-error from prod deploy on AKS
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3815 Add concurrency group and enable cancel-in-progress
  .github/workflows/aks_deploy.yml
Labels: azure-migration

#3837 Use `azure_enable_high_availability` instead of `postgres_enable_high_availability`
  terraform/aks/databases.tf
Labels: azure-migration, review-app

#3811 Update extended schedules guidance
  docs/source/ecf/schedules-and-milestone-dates.html.md
Labels: blocked-merge

#3599 Participant scenario testing seeds
  app/helpers/admin_helper.rb
  app/presenters/admin/participant_presenter.rb
  app/views/admin/participants/change_log/show.html.erb
  app/views/admin/participants/cohorts/show.html.erb
  app/views/admin/participants/declaration_history/show.html.erb
  app/views/admin/participants/details/show.html.erb
  app/views/admin/participants/history/show.html.erb
  app/views/admin/participants/identities/show.html.erb
  app/views/admin/participants/induction_records/show.html.erb
  app/views/admin/participants/school/show.html.erb
  app/views/admin/participants/statuses/show.html.erb
  app/views/admin/participants/validation_data/show.html.erb
  db/new_seeds/scenarios/cohorts/cohort.rb
  db/new_seeds/scenarios/induction_programmes/design_your_own.rb
  db/new_seeds/scenarios/lead_providers/lead_provider.rb
  db/new_seeds/scenarios/participants/ects/ect_after_cohort_transfer.rb
  db/new_seeds/scenarios/participants/ects/ect_in_training.rb
  db/new_seeds/scenarios/participants/ects/ect_no_validation.rb
  db/new_seeds/scenarios/participants/training_record_states.rb
  db/new_seeds/scenarios/school_cohorts/design_your_own.rb
  db/new_seeds/scenarios/school_cohorts/fip.rb
  db/new_seeds/scenarios/school_cohorts/no_early_career_teachers.rb
  db/new_seeds/scenarios/schools/school.rb
  spec/factories/seeds/core_induction_programme_factory.rb
  spec/factories/seeds/finance_milestone_factory.rb
  spec/features/scenarios/participants/ect_doing_cip/after_cohort_transfer_spec.rb
  spec/features/scenarios/participants/ect_doing_cip/in_training_spec.rb
  spec/features/scenarios/participants/ect_doing_cip/no_validation_spec.rb
  spec/features/scenarios/participants/ect_doing_fip/after_cohort_transfer_spec.rb
  spec/features/scenarios/participants/ect_doing_fip/in_training_spec.rb
  spec/features/scenarios/participants/ect_doing_fip/no_validation_spec.rb
  spec/features/schools/participants/add_participants/reporting_participants_with_trn_spec.rb
  spec/features/schools/participants/update_participants_details_spec.rb
  spec/helpers/admin_helper_spec.rb
  spec/lib/site_prism/table.rb
  spec/lib/site_prism/table/definition.rb
  spec/lib/site_prism/table/element.rb
  spec/services/determine_training_record_state_spec.rb
  spec/support/features/apis/ecf_participants_endpoint.rb
  spec/support/features/apis/ecf_users_endpoint.rb
  spec/support/features/apis/participants_endpoint.rb
  spec/support/features/pages/admin_support/admin_support_participant_detail.rb
  spec/support/features/pages/admin_support/admin_support_participant_training.rb
  spec/support/features/pages/appropriate_body/appropriate_body_portal.rb
  spec/support/features/pages/base_page.rb
  spec/support/features/pages/delivery_partner/delivery_partner_portal.rb
  spec/support/features/pages/finance/finance_participant_drilldown.rb
  spec/support/features/pages/finance/finance_participant_drilldown_search.rb
  spec/support/features/pages/finance/finance_payment_breakdown_report.rb
  spec/support/features/pages/schools/school_dashboard_page.rb
  spec/support/features/pages/schools/school_participant_details_page.rb
  spec/support/features/pages/schools/school_participants_dashboard_page.rb
  spec/support/features/steps/changes_of_circumstance_steps.rb
  spec/support/shared_examples/ecf_participant_record_scenarios.rb
  spec/support/with_training_record_state_examples.rb
Labels: blocked-merge

#3859 Remove mocks from seeds as not required
  db/new_seeds/scenarios/cohorts/cohort.rb
Labels: review-app

#3848 Add steps for restoring PaaS databases on Azure
  .github/workflows/backup-paas-database.yml
  .github/workflows/restore-backup-to-aks.yml
  Makefile
Labels: azure-migration

#3864 Schedule backups from PaaS to Azure
  .github/workflows/backup-paas-database.yml
  .github/workflows/backup-paas-schedule.yml
Labels: azure-migration

#3847 [CPDLP-2367] Automate monitoring and alerting for Sidekiq
  .env.template
  app/jobs/detect_sidekiq_metrics_issues_job.rb
  app/jobs/sidekiq_slack_notification_job.rb
  config/credentials/deployed_development.yml.enc
  config/credentials/production.yml.enc
  config/environments/deployed_development.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/sandbox.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/sidekiq.yml
  config/sidekiq_cron_schedule.yml
  spec/jobs/detect_sidekiq_metrics_issues_job_spec.rb
  spec/jobs/sidekiq_slack_notification_job_spec.rb
Labels: review-app

#3866 Make destroy review app action run for all PRs
  .github/workflows/aks_destroy_review.yml
Labels: azure-migration

#3888 Split backup workflow into separate actions
  .github/actions/backup-paas-database/action.yml
  .github/actions/restore-paas-database/action.yml
  .github/workflows/backup-paas-database.yml
  .github/workflows/backup-paas-schedule.yml
Labels: azure-migration

#3905 Remove the deploy to dev workflow
  .github/workflows/deploy_to_dev.yml
Labels: azure-migration

#3906 Set dates for banner for staging migration
  app/components/banners/maintenance_component.rb
Labels: azure-migration

#3907 Remove the staging sync step from backup flow
  .github/workflows/backup-paas-schedule.yml
Labels: azure-migration

#3915 Reset banner maintenance times
  app/components/banners/maintenance_component.rb
Labels: azure-migration
