Repository DFE-Digital/early-careers-framework, pull requests merged in 2023-06, with the labels that each got.

#3504 Patch show relevant training status
  app/views/admin/participants/details/_show_ecf.html.erb
  app/views/admin/participants/statuses/show.html.erb
Labels: enhancement

#3498 Handle deleted record entities in participant change log
  app/components/admin/participants/audit_trail_component.html.erb
  app/components/admin/participants/audit_trail_component.rb
  app/components/admin/participants/audit_trail_item_component.html.erb
  app/components/admin/participants/audit_trail_item_component.rb
  app/services/participants/history_builder.rb
  app/views/admin/participants/change_log/show.html.erb
  spec/services/participants/history_builder_spec.rb
  spec/support/with_support_for_ect_examples.rb
Labels: bug

#3569 Handle user types without error in change log
  app/components/admin/participants/audit_trail_component.html.erb
  app/components/admin/participants/audit_trail_component.rb
  app/components/admin/participants/audit_trail_item_component.rb
  app/services/participants/history_builder.rb
  spec/components/admin/participants/audit_trail_component_spec.rb
Labels: bug

#3563 AKS - add review app config
  Makefile
  global_config/review_aks.sh
  terraform/aks/development_aks.tfvars
  terraform/aks/review_aks.tfvars
  terraform/aks/review_aks.tfvars.json
Labels: azure-migration

#3585 Add Redis in AKS
  terraform/aks/cluster_data.tf
  terraform/aks/databases.tf
  terraform/aks/providers.tf
  terraform/aks/variables.tf
Labels: azure-migration

#3587 Add Azure Resource Mananger to AKS Proiders
  terraform/aks/providers.tf
Labels: azure-migration
